deployment:
  tasks:
    - export DEPLOYPATH=/home/mpqptrjm/aahaapps_testing

    # ----------------------------
    # Build frontend
    # ----------------------------
    - cd $DEPLOYPATH/client
    - npm install
    - npm run build

    # ----------------------------
    # Move build to server/public
    # ----------------------------
    - rm -rf $DEPLOYPATH/server/public
    - mkdir -p $DEPLOYPATH/server/public
    - cp -R dist/* $DEPLOYPATH/server/public/

    # ----------------------------
    # Install backend dependencies
    # ----------------------------
    - cd $DEPLOYPATH/server
    - npm install

    # ----------------------------
    # Restart Node app
    # ----------------------------
    - touch $DEPLOYPATH/server/tmp/restart.txt
