deployment:
  tasks:
    - /bin/echo "--- STARTING DEPLOYMENT FROM $(pwd) ---"
    
    # 1. Install Server Dependencies
    - cd server && npm install --production
    
    # 2. Deploy Frontend Build (Relative Paths)
    # We remove the old public folder and copy the new dist folder content
    - /bin/rm -rf server/public
    - /bin/mkdir -p server/public
    - /bin/cp -R client/dist/* server/public/

    # 3. Ensure Uploads Directory Exists
    - /bin/mkdir -p server/uploads

    # 4. Restart Node App
    - /bin/mkdir -p server/tmp
    - /bin/touch server/tmp/restart.txt
    
    - /bin/echo "--- DEPLOYMENT COMPLETE ---"
