deployment:
  tasks:
    - export DEPLOYPATH=/home/mpqptrjm/aahaapps_testing

    - echo "=== Building frontend ==="
    - cd $DEPLOYPATH/client
    - npm install
    - npm run build

    - echo "=== Copying build to server/public ==="
    - rm -rf $DEPLOYPATH/server/public
    - mkdir -p $DEPLOYPATH/server/public
    - cp -R $DEPLOYPATH/client/dist/* $DEPLOYPATH/server/public/

    - echo "=== Installing backend deps ==="
    - cd $DEPLOYPATH/server
    - npm install

    - echo "=== Restarting Node app ==="
    - touch $DEPLOYPATH/server/tmp/restart.txt
