deployment:
  tasks:
    - export DEPLOYPATH=/home/mpqptrjm/aaha_main_backend_node

    # Clean previous backend files (safe)
    - rm -rf $DEPLOYPATH/routes
    - rm -rf $DEPLOYPATH/controllers
    - rm -rf $DEPLOYPATH/models
    - rm -rf $DEPLOYPATH/middleware
    - rm -f  $DEPLOYPATH/server.js
    - rm -f  $DEPLOYPATH/package.json
    - rm -f  $DEPLOYPATH/package-lock.json

    # Copy backend to root
    - cp -R server/* $DEPLOYPATH/

    # Install backend deps
    - cd $DEPLOYPATH
    - npm install

    # Build frontend
    - cd client
    - npm install
    - npm run build

    # Replace public folder
    - rm -rf $DEPLOYPATH/public
    - mkdir -p $DEPLOYPATH/public
    - cp -R dist/* $DEPLOYPATH/public/

    # Restart Node app
    - touch $DEPLOYPATH/tmp/restart.txt
